#!/bin/sh
# Compile data/assets.tsv into src/assetinfo.h.
#
#   tools/make_assetinfo.sh -o src/assetinfo.h     (atomic; recommended)
#   tools/make_assetinfo.sh > src/assetinfo.h      (truncates on failure)
#
# Same reasoning as the registry: the browser has to describe a file and know
# whether it is recommended while drawing a frame, so neither can involve
# reading a file it has to locate first or a network call. The TSV stays the
# reviewable source of truth -- a diff against it is readable, which a C
# string table is not.
#
# Needs no network. Run it after editing the TSV, then rebuild.
set -eu

# With -o, write to a temp file and move it into place only on success. The
# shell truncates the target of a `>` redirect before the script runs, so a
# mid-run failure would leave a broken header and the previous contents
# recoverable only from git.
out=""
if [ "${1:-}" = "-o" ]; then
    out=${2:?-o needs a path}
    shift 2
fi

cd "$(dirname "$0")/.."
src=data/assets.tsv

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT INT TERM
if [ -n "$out" ]; then
    case "$out" in
        /*) ;;                       # absolute: use as given
        *) out="$PWD/$out" ;;        # relative: we just cd'd, so anchor it
    esac
    exec > "$work/out.h"
fi

if [ ! -f "$src" ]; then
    echo "make_assetinfo.sh: missing $src" >&2
    exit 1
fi

cat <<'EOF'
/* assetinfo.h -- GENERATED by tools/make_assetinfo.sh. Do not edit.
 *
 * Regenerate with:  tools/make_assetinfo.sh > src/assetinfo.h
 * The source of truth is data/assets.tsv.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2021-present Wanding Zhou
 */
#ifndef _YAME_ASSETINFO_H
#define _YAME_ASSETINFO_H

#include <stddef.h>

/**
 * What a file in the catalogue is, beyond its name.
 *
 * Keyed on what the browser derives from a filename: a knowledgebase set name
 * (the part before the first dot), or the role of a file that comes with a
 * platform or a genome (ordering, coord, mask, cpg_nocontig, ...). Either way
 * one entry covers every platform and build publishing it.
 * `recommend` lists the collections whose recommended selection includes it.
 */
typedef struct {
    const char *key;
    const char *collections;
    const char *recommend;
    const char *title;
    const char *biology;
    const char *source;
    const char *citation;
    const char *processing;
} yame_assetinfo_t;

static const yame_assetinfo_t YAME_ASSETINFO[] = {
EOF

python3 - "$src" <<'PY'
import sys, csv

path = sys.argv[1]
rows = []
with open(path) as fh:
    for line in fh:
        if line.startswith("#") or not line.strip():
            continue
        # rstrip("\r\n"), not just "\n": a TSV saved with CRLF would otherwise
        # carry a trailing CR into the last field of every row, and c() escapes
        # only backslash and quote, so it would land raw inside a C string.
        parts = line.rstrip("\r\n").split("\t")
        if parts and parts[0] == "key":      # the header row
            continue
        while len(parts) < 8:
            parts.append("")
        rows.append(parts[:8])

def c(s):
    # .strip() removes an interior-field CR too, for the same reason.
    s = (s or "").strip()
    # "?" is an acknowledged gap, not an empty field. Rendering it rather than
    # dropping it is the difference between "nobody knows" and "nobody looked"
    # -- and the browser omits empty fields entirely, so dropping it would say
    # the wrong one.
    if s == "?":
        s = "not recorded"
    return s.replace("\\", "\\\\").replace('"', '\\"')

for r in sorted(rows, key=lambda x: x[0].lower()):
    print('    { "%s", "%s", "%s",' % (c(r[0]), c(r[1]), c(r[2])))
    print('      "%s",' % c(r[3]))
    print('      "%s",' % c(r[4]))
    print('      "%s",' % c(r[5]))
    print('      "%s",' % c(r[6]))
    print('      "%s" },' % c(r[7]))
PY

cat <<'EOF'
    { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }
};

/** Metadata for a key, or NULL when we have none recorded. */
static inline const yame_assetinfo_t *yame_assetinfo_find(const char *key) {
    if (!key) return NULL;
    for (const yame_assetinfo_t *k = YAME_ASSETINFO; k->key; ++k) {
        const char *a = k->key, *b = key;
        while (*a && *b) {
            char ca = *a, cb = *b;
            if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
            if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
            if (ca != cb) break;
            ++a; ++b;
        }
        if (!*a && !*b) return k;
    }
    return NULL;
}

/** Is `key` part of `collection`'s recommended selection? */
static inline int yame_assetinfo_recommended(const char *key,
                                          const char *collection) {
    const yame_assetinfo_t *k = yame_assetinfo_find(key);
    if (!k || !k->recommend || !*k->recommend || !collection) return 0;

    size_t want = 0;
    while (collection[want]) ++want;

    const char *p = k->recommend;
    while (*p) {
        const char *comma = p;
        while (*comma && *comma != ',') ++comma;
        size_t len = (size_t)(comma - p);
        if (len == want) {
            size_t i = 0;
            while (i < len && p[i] == collection[i]) ++i;
            if (i == len) return 1;
        }
        if (!*comma) break;
        p = comma + 1;
    }
    return 0;
}

#endif /* _YAME_ASSETINFO_H */
EOF

if [ -n "$out" ]; then
    exec >&2
    mv "$work/out.h" "$out"
    echo "make_assetinfo.sh: wrote $out"
fi
