#!/usr/bin/env python3
"""Fill the two generated tabs of docs/index.html: Data and Reference.

Neither tab is written by hand, so neither can drift from what it describes:

  Data       from tools/registry/files.tsv, the table `yame fetch` is
             compiled from. One card per upstream host (GitHub repo or
             HuggingFace repo, at its pinned tag, with any Zenodo
             archive), a folded drawer per store directory, and in it a
             folded entry per file: its description split into labelled
             paragraphs at its [Label] markers, then source and citation.
             One line under each directory lists the works it cites.
  Reference  from `./yame <command> -h`, for every command the `yame`
             banner lists, grouped as the banner groups them. Each entry
             has the id `ref-<command>`, so a link to #ref-pack opens it.

The binary runs under a FIXED environment (HOME=/home/user, no store or XDG
variables), because the banner and `fetch -h` print the resolved store path
and the page must not depend on whose machine built it.

    docs/build_docs.py            rewrite docs/index.html in place
    docs/build_docs.py --check    exit 1 if the page is behind either source

`make docs` runs it; `make docs-check` runs --check. Same shape as the
Reference tab of sesame and methscope.
"""
import html, os, re, subprocess, sys
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "index.html")
TSV = os.path.join(ROOT, "tools", "registry", "files.tsv")
BIN = os.environ.get("YAME_BIN") or os.path.join(ROOT, "yame")
ENV = {"HOME": "/home/user", "PATH": os.environ.get("PATH", ""), "LANG": "C"}

HELP_BEGIN = "<!-- help:begin (generated by docs/build_docs.py from `yame <command> -h`) -->"
HELP_END = "<!-- help:end -->"
DATA_BEGIN = "<!-- data:begin (generated by docs/build_docs.py from tools/registry/files.tsv) -->"
DATA_END = "<!-- data:end -->"

esc = lambda s: html.escape(s, quote=False)
attr = lambda s: html.escape(s, quote=True)

## ---- Reference: every command's -h ----

def run(*args):
    p = subprocess.run([BIN, *args], capture_output=True, text=True, env=ENV,
                       stdin=subprocess.DEVNULL)
    return (p.stdout + p.stderr).strip("\n")

def banner_sections():
    """[(section, [(name, desc), ...]), ...] as the bare `yame` banner groups
    them: a section is an unindented line ending in a colon, an entry a
    2-space-indented `name  desc`, and a deeper-indented line continues the
    entry above it."""
    out, cur = [], None
    for line in run().splitlines():
        if not line.strip(): continue
        if not line.startswith(" "):
            cur = (line.strip().rstrip(":"), []) if line.rstrip().endswith(":") else None
            if cur: out.append(cur)
            continue
        if not cur or cur[0] == "Usage": continue
        m = re.match(r"^ {2}(\S+)\s{2,}(.+)$", line)
        if m: cur[1].append([m.group(1), m.group(2).strip()])
        elif cur[1]: cur[1][-1][1] += " " + line.strip()
    return [(h, c) for h, c in out if c]

def help_entry(name, desc):
    return ('  <details class="cmd" id="ref-%s">\n'
            '    <summary><code class="inl">yame %s</code> <span class="m">— %s</span></summary>\n'
            '    <pre class="help"><code>%s</code></pre>\n  </details>'
            % (name, name, esc(desc), esc(run(name, "-h"))))

def build_help():
    out, n = [HELP_BEGIN], 0
    for heading, cmds in banner_sections():
        out.append('<section class="card">\n  <h2>%s</h2>' % esc(heading))
        for name, desc in cmds:
            out.append(help_entry(name, desc)); n += 1
        out.append('</section>')
    out.append(HELP_END)
    return "\n".join(out), "%d commands" % n

## ---- Data: what fetch offers, from files.tsv ----

def read_registry():
    cols = ["key", "store_path", "sha256", "size", "rows", "kind",
            "title", "description", "source", "citation"]
    rows = []
    for line in open(TSV, encoding="utf-8"):
        if line.startswith("#") or not line.strip(): continue
        r = dict(zip(cols, line.rstrip("\n").split("\t")))
        src_tag, _, remote = r["key"].rpartition(":")
        src, _, tag = src_tag.rpartition("@")
        r.update(src=src, tag=tag, remote=remote,
                 dir=os.path.dirname(r["store_path"]),
                 size=int(r["size"] or 0))
        rows.append(r)
    return rows

def host(src, tag):
    """(host label, repo url, url of the pinned tag) for a registry source."""
    if src.startswith("hf:"):
        repo = src[3:]
        return ("HuggingFace", "https://huggingface.co/" + repo,
                "https://huggingface.co/%s/tree/%s" % (repo, tag))
    return ("GitHub", "https://github.com/" + src,
            "https://github.com/%s/tree/%s" % (src, tag))

def human(n):
    """Bytes as `yame fetch` prints them (yame_human_size): a 1024 ladder, one
    decimal, so a size on the page matches the terminal and methscope's page."""
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return ("%d %s" % (n, u)) if u == "B" else ("%.1f %s" % (n, u))
        n /= 1024.0

def zenodo(rs):
    """The Zenodo archive DOIs a host's files cite, in first-seen order."""
    return list(OrderedDict.fromkeys(
        d for r in rs for d in re.findall(r"10\.5281/zenodo\.\d+", r["citation"])))

## A description is one TSV field, so its sections are marked inline, as a
## bracketed label at a sentence start ("... [Training] Trained on ...").
## The text before the first label is what the file IS. Same rule as
## methscope's docs/build_models.py, so a model reads the same on both pages.
SECTION = re.compile(r"(?:^|\s)\[([A-Z][A-Za-z ]{1,30})\] ")

def sections(text):
    """[(label, text)]: 'What it is' first, then one per [Label], in order."""
    parts = SECTION.split(text)
    out = [("What it is", parts[0].strip())]
    out += [(parts[i], parts[i + 1].strip()) for i in range(1, len(parts), 2)]
    return [(l, t) for l, t in out if t]

def linked(text):
    """Escape, then link every `doi:10.x/y` and bare Zenodo DOI."""
    return re.sub(r"(doi:)?(10\.(?:5281/zenodo\.\d+|\S+?(?=[,;)]|\s|$)))",
                  lambda m: '<a href="https://doi.org/%s" rel="noopener">%s</a>'
                  % (attr(m.group(2)), m.group(0))
                  if m.group(1) or "zenodo" in m.group(2) else m.group(0),
                  esc(text))

def file_entry(f):
    """One file: a one-line summary (name, title, size) that opens onto its
    description, a labelled paragraph per section, then source and citation."""
    body = ['      <p><b>%s.</b> %s</p>' % (esc(l), esc(t))
            for l, t in sections(f["description"])]
    if f["source"]: body.append('      <p><b>Source.</b> %s</p>' % esc(f["source"]))
    if f["citation"]: body.append('      <p><b>Citation.</b> %s</p>' % linked(f["citation"]))
    return ('    <details class="file">\n'
            '      <summary><code>%s</code><span>%s</span><span class="n">%s</span></summary>\n'
            '%s\n    </details>'
            % (esc(os.path.basename(f["store_path"])), esc(f["title"]),
               human(f["size"]), "\n".join(body)))

def cites(fs):
    """The works a directory's files cite, as short linked labels
    (`Zheng 2019`), deduplicated in table order. A Zenodo archive note is
    left out: the Hosts table already carries it."""
    out = OrderedDict()
    for f in fs:
        for part in f["citation"].split(";"):
            part = part.strip()
            if not part or part.startswith("Archived"): continue
            who = re.match(r"[A-Z][\w-]*", part)
            year = re.search(r"\b(1[89]|20)\d\d\b", part)
            doi = re.search(r"doi:(10\.\S+?)(?=[,;)]|\s|$)", part)
            label = (who.group(0) if who else part) + (" " + year.group(0) if year else "")
            out.setdefault(label, doi.group(1) if doi else None)
    return " · ".join('<a href="https://doi.org/%s" rel="noopener">%s</a>'
                      % (attr(d), esc(l)) if d else esc(l)
                      for l, d in out.items())

def build_data():
    rows = read_registry()
    hosts = OrderedDict()                 # src@tag -> rows, in table order
    for r in rows: hosts.setdefault((r["src"], r["tag"]), []).append(r)
    out = [DATA_BEGIN]

    ## one card per host, a drawer per store directory
    for (src, tag), rs in hosts.items():
        label, repo, tagurl = host(src, tag)
        name = src[3:] if src.startswith("hf:") else src
        dirs = OrderedDict()
        for r in rs: dirs.setdefault(r["dir"], []).append(r)
        ## the heading links the repo and its pinned tag; a Zenodo archive
        ## the files cite, if any, follows it
        arch = "".join(' · <a href="https://doi.org/%s" rel="noopener">%s</a>'
                       % (d, d.split("/")[1]) for d in zenodo(rs))
        out.append('<section class="card">\n  <h2><a href="%s" rel="noopener">%s</a>'
                   ' <span class="m">— %s @ <a href="%s" rel="noopener">%s</a>%s</span></h2>'
                   % (attr(repo), esc(name), label, attr(tagurl), esc(tag), arch))
        for d, fs in dirs.items():
            out.append('  <details class="dir" id="data-%s">\n'
                       '    <summary><code class="inl">%s/</code> <span class="m">— %d files, %s</span></summary>'
                       % (attr(d.replace("/", "-")), esc(d), len(fs),
                          human(sum(f["size"] for f in fs))))
            for f in fs: out.append(file_entry(f))
            c = cites(fs)
            if c: out.append('    <p class="cites">Cites: %s</p>' % c)
            out.append('  </details>')
        out.append('</section>')

    out.append(DATA_END)
    return "\n".join(out), "%d files, %d hosts" % (len(rows), len(hosts))

## ---- splice ----

def splice(page, begin, end, block):
    i, j = page.find(begin), page.find(end)
    if i < 0 or j < 0: sys.exit("build_docs.py: markers %r not found in docs/index.html" % begin[:14])
    return page[:i] + block + page[j + len(end):]

def main():
    page = open(PAGE, encoding="utf-8").read()
    new, notes = page, []
    for begin, end, build in ((DATA_BEGIN, DATA_END, build_data),
                              (HELP_BEGIN, HELP_END, build_help)):
        block, note = build()
        new = splice(new, begin, end, block); notes.append(note)
    if "--check" in sys.argv:
        if new != page: sys.exit("docs/index.html Data/Reference tabs are behind files.tsv or the binary: run `make docs`")
        print("  ok   Data and Reference tabs are current (%s)" % "; ".join(notes)); return
    if new != page:
        open(PAGE, "w", encoding="utf-8").write(new); print("rendered %s into docs/index.html" % "; ".join(notes))
    else:
        print("docs unchanged")

if __name__ == "__main__": main()
