/* registry.h -- GENERATED by tools/make_registry.sh --tool=yame. Do not edit.
 *
 * What `yame fetch` knows how to download, and the digest each directory's
 * manifest must have. One row per fetchable directory.
 *
 * store_sub is the browser path: what the tree shows under a name is what
 * lands under that name in the store, so `hg38/data` in the browser is
 * <root>/hg38/data on disk. Which upstream repo filled a directory is in
 * `source`, not in the path.
 *
 * The anchor is sha256(SHA256SUMS) at the pinned tag, hashed from the copy
 * cached under tools/registry/sums/. Verifying a fetched manifest against it
 * is what makes every per-file digest trustworthy, and comparing a STORED
 * manifest against it is how a directory says which tag filled it.
 *
 * `prior` is the same hash for every EARLIER tag still cached in the repo.
 * Without it a store one tag behind is indistinguishable from a store some
 * other tool filled, and both need -f; with it, catching up is just a fetch.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2021-present Wanding Zhou
 */
#ifndef _YAME_REGISTRY_H
#define _YAME_REGISTRY_H

#include <stddef.h>
#include <stdint.h>

#include "assets.h"   /* yame_pin_prior_t */

/* One file a directory publishes, with the digest it must have.
 *
 * store_sub is normally the unit's, and NULL says so. It is set only where a
 * file belongs somewhere else in the store than the directory that publishes
 * it: a genome's cpg_nocontig.cr comes from the KYCGKB repo but is the
 * genome's index, so it lands at <genome>/ rather than <genome>/KYCG/. The
 * browser renders a file wherever this puts it, so the tree and the store
 * cannot drift apart. */
typedef struct {
    const char *name;
    const char *sha256;
    uint64_t    size;        /* 0 when upstream does not publish one */
    const char *store_sub;   /* NULL: the unit's own store_sub */
} yame_asset_file_t;

#define YAME_NFILES(t) (sizeof(t)/sizeof((t)[0]) - 1)
#define YAME_NPRIOR(t) (sizeof(t)/sizeof((t)[0]))

typedef struct {
    const char *source;      /* upstream repo family: InfiniumAnnotation, ... */
    const char *target;      /* platform, genome, or "<platform>/KYCG" */
    const char *base_url;    /* <base>/<tag>/<remote_sub>/SHA256SUMS */
    const char *tag;
    const char *remote_sub;  /* "" when the manifest is at the repo root */
    const char *store_sub;   /* path under the store root */
    const char *anchor;      /* sha256 of that directory's SHA256SUMS */
    const yame_asset_file_t *files;  /* what the directory holds */
    size_t      n_files;
    const yame_pin_prior_t *prior;   /* earlier tags this build supersedes */
    size_t      n_prior;
} yame_asset_reg_t;

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_EPIC[] = {
    { "EPIC.ordering.tsv.gz", "a55f9587ec0228406bb731a56bebb54bbde7f898d53c2afcfdd50b1b3e950d01", 7756709, NULL },
    { "EPIC.hg38.coord.tsv.gz", "08904e7dd06f0df739951eec6b672723021f2a25d704ead436145eff650703e7", 5505138, NULL },
    { "EPIC.hg38.snp.tsv.gz", "f4310e5314013dc83328600a9bcb0b1e0a544dc6e7d8bd0603a8a5a941885b4d", 1776995, NULL },
    { "EPIC.typeI_ext.tsv.gz", "e2ecbe9c7bc7610a298427bf623b9c5f881ab40aa7d47e89bf103d8d1222a4db", 91446, NULL },
    { "EPIC.hg38.mask.cm", "28a4d03b714fe84fb64985fd9ed4826c51f7d619e9361d249bbce80e3f0d447e", 365760, NULL },
    { "EPIC.hg38.mask.cm.idx", "bf0ba81485964e805f2c6652e5e1d336c895185c4391f500f23deba7eaa8e593", 733, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_EPIC_KYCG[] = {
    { "ABCompartment.20220911.cm", "8409adddd1cc9af9b40aa675c066932a93bedfa10672feada4505f57d45ec584", 401447, NULL },
    { "Blacklist.20220304.cm", "3482751b12d943a0ea42ceba244c7c9abdafeccea2492a00026f680bce14fce5", 1024, NULL },
    { "CGI.20220904.cm", "e5ab587e836d60c6bbaeb6c8005aeee306b0056130eb2111b6233cd38dea6f44", 320296, NULL },
    { "ChromHMM.20220303.cm", "37ebdae57c055a60c01bd50ed9d5599a0bc58479dc2a7dc429fd80040f55dfac", 472684, NULL },
    { "CTCFbind.20220911.cm", "985a609591373d672af84a0a094941e4081239c9006af03f7de97e420ebec371", 38289, NULL },
    { "HM.20221013.cm", "4ceff1553dfe657eb2d172e00fc14e8cc4961c9d1f54251fd4f4b1935e676bc4", 2365502, NULL },
    { "ImprintingDMR.20220818.cm", "251327619cdd323a39efc295dd263de5533fb74239b8b688ade86b295c564397", 2581, NULL },
    { "InfiniumChemistry.cm", "b0b860ca2d9f778a39934d624be0b6fe57a5892dda7da340b543edf4dd9d47ef", 170333, NULL },
    { "MetagenePC.20220911.cm", "9221b563693a499d71d8fcf6a4424ca6ef5a78494a87f45e3c84b7f0571ed94c", 1877298, NULL },
    { "nFlankCG.20220321.cm", "d06e17ea155a13decd6b66e3e964b616f3a6d374df974e301529ef59fb98ea8d", 660394, NULL },
    { "PMD.20220911.cm", "1df31b1475c068e6e277e9b8ebee9d1deefdcb27596d73d30a56940024cff2c6", 195686, NULL },
    { "ProbeType.cm", "50f5c8bae68b089c49d348359a523bdd88f7c5e11b8a52f102604ec6770fc841", 99, NULL },
    { "REMCChromHMM.20220911.cm", "a561f69f630b2fced0d6f8c1cd6874bba754cddd7a46e078ddd5ae1c391f857d", 470923, NULL },
    { "rmsk1.20220307.cm", "e5cc8d88235623b4aea2e79ef02b9d9c75d929358790d7eb7da3712c9cd4a896", 195568, NULL },
    { "rmsk2.20220321.cm", "e126b5c5a3b55fd349ea4d53a74d2e3c6396d019c326aa814fc97f5de7d1fdc4", 278780, NULL },
    { "Tetranuc2.20220321.cm", "ed32ee6d49f71443c4093d62821e6ff39c629d22f5149da10eba23bb2595de2f", 283378, NULL },
    { "TFBSrm.20221005.cm", "d7f430d5d40e0d1b1cd1c82afd6d06480a2748d524c3536d1723e34e34fd6847", 36004353, NULL },
    { "ABCompartment.20220911.cm.idx", "58897557f71dfbc08aec972eb05d4fd5340a8222cece8547644530e250af3a29", 79, NULL },
    { "CGI.20220904.cm.idx", "58177bee21bc996cc10cb171498ef1c94a345c5e6afddd2c8d544fabfe33e6f3", 64, NULL },
    { "HM.20221013.cm.idx", "35e3173a4970123836c5079ace51ea955d2c792d17b50a62bb41457992b8d93f", 1698, NULL },
    { "MetagenePC.20220911.cm.idx", "6c372278d5197935d2e20839990eaabfe529d6501a2e3cf0324730e513216e19", 762, NULL },
    { "nFlankCG.20220321.cm.idx", "b2be3226cca62c0d046183f319413654b835f27638ec65401b909714330038b8", 504, NULL },
    { "PMD.20220911.cm.idx", "7c53dc49fbe19027e3c6d706f3787dbceb937d83049b2aba7c1a301019ae075f", 33, NULL },
    { "rmsk1.20220307.cm.idx", "0a0194bda6aa4f54715e40bde2b7c491c57f35ed60f0f529e446959042ecfc5f", 352, NULL },
    { "rmsk2.20220321.cm.idx", "cf7d0044c2bc65f0ac706cc996df3fc3cb795f447179677e71673833f3f4dd9d", 1103, NULL },
    { "TFBSrm.20221005.cm.idx", "26b91319b7d1d72b17e23661ec315a0a754403b9654ac629d0aa86255ebe434b", 23486, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_EPICv2[] = {
    { "EPICv2.ordering.tsv.gz", "52f8c45dc9d90c59367e020489a295b4b0c4f434e20930c44fe6cc079ba2de7d", 8546436, NULL },
    { "EPICv2.hg38.coord.tsv.gz", "6c2213eff46a14a1cb414f60b2f12ec25bfce949c2419498a919c316aa9be12e", 5728827, NULL },
    { "EPICv2.hg38.snp.tsv.gz", "e4cef2b827abd0a6173c22715f56451f0e01722a5c32f2c8fe7077381220ee17", 1631893, NULL },
    { "EPICv2.typeI_ext.tsv.gz", "4872dab7ec1e8db7ed99c24a3990137478bdd8b659ea60f821230eb352692938", 89958, NULL },
    { "EPICv2.hg38.mask.cm", "7463ce67bb26904e8ef236f1befffbac8db1c2e4ac07fc3d6d7eb2b8072782d0", 301037, NULL },
    { "EPICv2.hg38.mask.cm.idx", "00b94541b3c8083d65e861ca1ccae1dc9a1093172591ea9c4dc539f3eadd290e", 760, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_EPICv2_KYCG[] = {
    { "ABCompartment.20220911.cm", "6a16dfdaea362cf08a5109de2a3db11872747eefb8763ed816edc4b32d7abc62", 429646, NULL },
    { "CGI.20220904.cm", "e98a31229f7661195a626eda5490bf00f56e701896ad01b780f643268ab2c826", 334456, NULL },
    { "ChromHMM.20220303.cm", "fca78dadf3388f5bcd9af60e08fbd443c42b89951d86b40edc8d7e97a0c8a209", 497071, NULL },
    { "CTCFbind.20220911.cm", "05c54e264e5b8612bd4540219767c5eca598e80ceeb2816493b691f750842161", 43704, NULL },
    { "HM.20221013.cm", "31f719b3b0f56aef1e8b49f5f30e58c3b4e73dd34901d761272262e8b94b406b", 2435825, NULL },
    { "ImprintingDMR.20220818.cm", "f050428048aab8dd37fe74b1e900e501ead7e8fc1b265ce152f2e733717d0a29", 2455, NULL },
    { "InfiniumChemistry.cm", "42784479915a0b2db51c2519e61f6d326a3d637162fcc0d67789fe3056e83373", 161445, NULL },
    { "MetagenePC.20220911.cm", "11b7166790d320bbc14897d4240653f8585d0f419cf9c580127661c8657e79af", 2011122, NULL },
    { "nFlankCG.20220321.cm", "06ee3efae120e25330b6fd34939cae07731e3101be954fb957f4ca3739367168", 643034, NULL },
    { "PMD.20220911.cm", "be2c7d0e8518bbea30f7a2f5611bb4bc4bbbda8cdef107549ef8c0880d71993d", 211343, NULL },
    { "ProbeType.cm", "aa07d4abed06c6512a92f083a85fe075a93564d1bbc441f63c5bc4dac22629e2", 105, NULL },
    { "REMCChromHMM.20220911.cm", "4b3887473b0412bf1ccdb22c3aec5554bc68c8bb62b74f6a3b8a95ad4e0a99c5", 496042, NULL },
    { "rmsk1.20220307.cm", "7ddc199531c7143b255f44a65726ab9372a8f7739842d128353ecedbe8612a30", 211617, NULL },
    { "rmsk2.20220321.cm", "2e8b1f44d61029b191c13576fc945f413db03091c023113d4c276ca64937c872", 302615, NULL },
    { "Tetranuc2.20220321.cm", "567b212b3d0c3984bb69e38c87784c5f001daea8d24ed982cf5935217b49033f", 307945, NULL },
    { "TFBSrm.20221005.cm", "84d1fab1f84a9608f9f439f7d8d06ab980ac0df1c55417e4cb5f93d1ccc591c1", 37609558, NULL },
    { "ABCompartment.20220911.cm.idx", "60b8e0b78cc83e818120fb94bd6276cef520c0df7ee8ae6a43776862dcb81741", 79, NULL },
    { "CGI.20220904.cm.idx", "6d73aaaec3f6e6aeed3dcef25c3ece7fe4f4947d029951c5ba95ddc80da5560f", 64, NULL },
    { "HM.20221013.cm.idx", "a5a12b94a858d6d3d3399d5a7a6c76b8524e8c9bd9dbfe8d4845e661726b58a8", 1699, NULL },
    { "MetagenePC.20220911.cm.idx", "e7c28f1a621274258ad376fffee7dc7c0ea038b0972f950db1977b43f870bea0", 764, NULL },
    { "PMD.20220911.cm.idx", "2454e78a6aabbe359502dfe68ee324fe85ccdf54f6732cf42247c9bca4901d6a", 33, NULL },
    { "rmsk1.20220307.cm.idx", "0848985e6400d539f2397638dec7a235ae96e40e490c0421e9e11b8de1c0a19f", 352, NULL },
    { "rmsk2.20220321.cm.idx", "8882e21a7ce1e35ce7dafeeb7d405d9dd3675f6f4936c25e22e0156b0a5816c4", 1104, NULL },
    { "TFBSrm.20221005.cm.idx", "86fd3b8030aab40e58b5fada2bdeebc309f280df06497596013b81748fe5eac7", 23502, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_HM27[] = {
    { "HM27.ordering.tsv.gz", "5efacd18ea2d68fcaea11be183c2b3ea8eee22b5253ded032cb4799ee2c5e1b3", 305538, NULL },
    { "HM27.hg38.coord.tsv.gz", "c3a722258116011af07e35e072c97676236df8d53eb73d54c89bc092c8f13f9f", 173651, NULL },
    { "HM27.hg38.snp.tsv.gz", "4f8ed780cff0a00a52fc5238f27f67e5faa2b3c89cbd2f6c8cd9ce3aad83553e", 358753, NULL },
    { "HM27.typeI_ext.tsv.gz", "092797d933639b5e4a48a73bef95be12bd9161b1a45582bbf03de3d33837a0b2", 3432, NULL },
    { "HM27.hg38.mask.cm", "9b70bb7dc8393219a5a7cdc95b558532bb0382dbb311c01fcc8056bc6e99f8c1", 7969, NULL },
    { "HM27.hg38.mask.cm.idx", "4a176255774d68ce1e687c1b2e3a71f4f1a6164445d950acb5c9472ca54cdfc4", 466, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_HM27_KYCG[] = {
    { "ABCompartment.20220911.cm", "c14476110702ce82dc33c6e76fcb4eeb89a81945342e118e5b6804d1b6d8fc8b", 12334, NULL },
    { "CGI.20220904.cm", "f183e6fcbe903ddb88a1c76fbeec2f93a357eb55d1951595c40e975d5eff7adb", 10623, NULL },
    { "ChromHMM.20220303.cm", "bac2754ceb8b10891368d9183ae85fc7bb08ffeb7718f9240862479f79a9b007", 14712, NULL },
    { "CTCFbind.20220911.cm", "4d5eb8099245f676b75e6f45099f04b0b601da9944284a4f2c833c57045e985a", 1619, NULL },
    { "HM.20221013.cm", "b0e6215dbd4d021e53f742444c0f45e0467c34239075aad3f1467a923b054868", 143275, NULL },
    { "ImprintingDMR.20220818.cm", "812cc9774e0afec39d4cbcca2ad331096ffa94b784c8eddf4f4d6cda80a3e8c3", 407, NULL },
    { "InfiniumChemistry.cm", "2f698be22c096454d6f89dceaa962e1a62fba12df150ba25c3ba03951964d5be", 8461, NULL },
    { "MetagenePC.20220911.cm", "659d360d94a22806926a73daa1b1e363bb32a7af74c5e54351a10d28b2096fd4", 64127, NULL },
    { "nFlankCG.20220321.cm", "4085f0190cbc97b030e322001ebd8f18cd5a044e0725054fa03b250fa125322a", 22006, NULL },
    { "PMD.20220911.cm", "16ce9621091143e7868e9d6a79a7a8e855a4593a8dc85bcb33f6274bc5140702", 8753, NULL },
    { "ProbeType.cm", "468a75c68f3a7492541c09680eb11275b3d62b2456c194473613fae2051f5986", 83, NULL },
    { "REMCChromHMM.20220911.cm", "6d89d1e4eb45b48af9cdd37987d57d424d46d4eff5a8a4ccd28cafb40f1011bd", 13398, NULL },
    { "rmsk1.20220307.cm", "68f5a992465534f8d435a8da2e5b0db4cdbfd8e4b7730be8c99385187dd138dd", 5127, NULL },
    { "rmsk2.20220321.cm", "8f21d6cb4c93d425f04a856c223e4a1cdff52b8a934de226843401f43d8604bb", 8509, NULL },
    { "Tetranuc2.20220321.cm", "8abfdf24af0250214d4ee82a9eec2d88087bf61868ca6dceba57d5f8a2b7af8c", 8911, NULL },
    { "CGI.20220904.cm.idx", "e2be8ef071092bc8c7d067ec1b1780c1a32d9e44737563f0960b7f7ab8aca9ec", 59, NULL },
    { "HM.20221013.cm.idx", "88e484b5f785a36a8a8209aff0802bbbedcb8222f0d353ec13d708809431c37d", 1565, NULL },
    { "MetagenePC.20220911.cm.idx", "36ba9e7aa87453af12550f4fd553bc01223b6e06dcdbb9d49ece91ace6df7b44", 724, NULL },
    { "rmsk1.20220307.cm.idx", "7981bd0482797c1bad131153ff1890b3556ef1c6b94cce68d2324ebb43cd0d07", 229, NULL },
    { "rmsk2.20220321.cm.idx", "11bc84e3688286502d06396eb2489354c93be9076dd4ba89408e26bb943b1bc3", 682, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_HM450[] = {
    { "HM450.ordering.tsv.gz", "e5106a34e970f61b36fc70661239c4a1176c816f13af6a5dde61db9b2af9ae44", 4583238, NULL },
    { "HM450.hg38.coord.tsv.gz", "bedd968a41a2f287e18d94c86f34d46fd640086bd3c43639bd0a878ea64f3a40", 3064215, NULL },
    { "HM450.hg38.snp.tsv.gz", "3ad6d0226b9dc928f65ed028a6bca59d91a53a6803e66e4645a8f97cd42f5a7e", 1697522, NULL },
    { "HM450.typeI_ext.tsv.gz", "dd223d6672d5fd0388048d9d9862be6947bac3b5e3effb088f16da90582d1c4b", 72943, NULL },
    { "HM450.hg38.mask.cm", "adebc62a6e6c1a783a5cd00bf61b441ee2b72c017d7be978fbf2ee6334d04360", 213674, NULL },
    { "HM450.hg38.mask.cm.idx", "27dff6eb30329c3fc974226a8da3e2b8d5d66f4205abde8eebb78fb07e28b959", 727, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_HM450_KYCG[] = {
    { "ABCompartment.20220911.cm", "bc987449f66822386910060aeeeab4ea55f9d59c19cd914e3f955549146ea6c0", 222018, NULL },
    { "Blacklist.20220304.cm", "d94fdffae9a0f97663439581baf3a942ef25066c6ef0a93a8d59b674f98d5888", 730, NULL },
    { "CGI.20220904.cm", "61acf5ef9d4c77819d1e4ec363b0d62e1608697b8b2062422cec74633e6c9c7a", 195724, NULL },
    { "ChromHMM.20220303.cm", "86168106af9881c786780424fb2790578626d1dbb83401617aa09f3fa68806d1", 289807, NULL },
    { "Chromosome.20221129.cm", "0e95b6c6fdf99ec1e60d6545819746dfc8453fe258652e8a6e83d9b204a1d8c6", 375096, NULL },
    { "CTCFbind.20220911.cm", "26193240856d11fc4d1139674f3532cb5ee5643dcdcbdf1077768991f8f0a14c", 22325, NULL },
    { "HM.20221013.cm", "43f939a3f33c7a8d29777f1d6b2ff3b7f5673819c72ccd7cf51b71a233c9bc06", 1630916, NULL },
    { "ImprintingDMR.20220818.cm", "20dbef3ba8b4504d7c2e3c512983f928a9f6cdac98e1abb6eb641f1d844bf77c", 2322, NULL },
    { "InfiniumChemistry.cm", "2a4e1074a5614cfdaa110309fb9ba7f29ca91d34f203840b0a155d1e121d9f42", 138065, NULL },
    { "MetagenePC.20220911.cm", "983b5a7b7ad01d19b78ec98f7cf2fa6a39778516c7713b45be6ad32693226f46", 1086937, NULL },
    { "nFlankCG.20220321.cm", "a6b4f9781cc492ae9828b7a529f162cd5dd09b350f4f8c372c7d5500600f5d56", 423959, NULL },
    { "PMD.20220911.cm", "3d1db833178e3cdb819f6484b7589d0d8de949dbd6cc4db172d1019f681c85bc", 108540, NULL },
    { "ProbeType.cm", "14d63c7c39c41eb25e353c843404c20cac80d4c0756b1cf0df23f9ca948696bf", 108, NULL },
    { "REMCChromHMM.20220911.cm", "96d20824e20f127ddeba6e0709e6ac60adf2713c0b73ecbbf0fa276ca6ecec45", 279823, NULL },
    { "rmsk1.20220307.cm", "2c08e45672733e9a77c7da660a1e13484b8aaf37b99a5cd6bb346dfccb9d71c9", 94893, NULL },
    { "rmsk2.20220321.cm", "7f899fbb7eabc3ccd7c16ea5ed0eeb4eb2bafbec3eb1e1b4c98428271c42f6aa", 130105, NULL },
    { "Tetranuc2.20220321.cm", "86137cf2c32900e07b5a43eca47eabfb3a4796266f2ddc425eb8eefb4370d9b2", 154671, NULL },
    { "TFBSrm.20221005.cm", "d207dab0fe897ca64895da7acd9d1b833704607fe39957473173a0c3376c6782", 24361394, NULL },
    { "ABCompartment.20220911.cm.idx", "12a6797ee54d07dd58a608812f712e55457922d192c2697999524508efd81e39", 77, NULL },
    { "CGI.20220904.cm.idx", "2f7b42d917aacd2d671dd3bd30c0993fbeb92ad84ba1fd736de566870dae72a7", 62, NULL },
    { "HM.20221013.cm.idx", "5230d49e67b8e4fdd5ed36915703df62af857543d765d9a5a27c4fffc861cc49", 1672, NULL },
    { "MetagenePC.20220911.cm.idx", "7b238ce7df7e7d06d96b025a1a73a34d68741ba29fd6ee4d6d03fa088040688b", 755, NULL },
    { "nFlankCG.20220321.cm.idx", "b4a85351532d892422dc210a54f83cc7d870ef8af1c92e4730bc9a643643651d", 484, NULL },
    { "PMD.20220911.cm.idx", "a0807f56d7e8cdadd170522ab3feb603d89981a9bfbdaa03c9b9fc085cc84db6", 33, NULL },
    { "rmsk1.20220307.cm.idx", "8ed5e5f57f705d8eab86ee1a236b809b19aa042d8fb41f4142fd6d91180df763", 341, NULL },
    { "rmsk2.20220321.cm.idx", "53c39a208aa4975f6f193755f70611daaf71dd4ba9c55fd939e7923689eb6378", 1021, NULL },
    { "TFBSrm.20221005.cm.idx", "09e2b0a57a0f18948058354229f7e7b7c1128da919b64d691bc743d8acda3993", 23244, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_Mammal40[] = {
    { "Mammal40.ordering.tsv.gz", "45a6133ddc4aa2201d40d4b56257f860e22187c17d8511d9ac2ab417e2d60a77", 345271, NULL },
    { "Mammal40.hg38.coord.tsv.gz", "f423afb64542256a4693f67ef9b5c36342354ec34e92aec001b493ffd9a1d8a7", 234668, NULL },
    { "Mammal40.hg38.snp.tsv.gz", "f10aee3b81bd237c17cf4155963097cf9d28e898e006126f1215929ee6a94518", 37107, NULL },
    { "Mammal40.typeI_ext.tsv.gz", "36965921d5f7a2789d4d3aa8d9ecb08efc7313adfb47235a7076e6b7247c3c52", 2576, NULL },
    { "Mammal40.hg38.mask.cm", "ed5422e9a264496500aae6b6defbc96dd18789ceb79dd603ec50b157fba48e17", 11659, NULL },
    { "Mammal40.hg38.mask.cm.idx", "186d9999594856de040339e45021b4be41caadcfe0924465b1d230ac00d3250a", 629, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_Mammal40_KYCG[] = {
    { "ABCompartment.20220911.cm", "c9c09cd480456bf871d99a44dbfaa9ea0629c2dbcb13013c817fd6daff2e448b", 18320, NULL },
    { "CGI.20220904.cm", "1cc641f0ab67aaa5b2af229638104de593b77e08e9de3a1abbd81fbbf571670a", 13039, NULL },
    { "ChromHMM.20220303.cm", "9e7bd9d801a256b42429d1a1724b1deda6edbcabe881d083e6f9f08d16e65a35", 20962, NULL },
    { "CTCFbind.20220911.cm", "b89bd34b01b1e2c004aa11e6fdf0391ad3143fb81cfd6d24d395bedd91ed9e35", 1147, NULL },
    { "HM.20221013.cm", "8cb5f6caff50236af2221ad3c63c005f76dba6e2218fb2746b9c16316c9a094f", 82050, NULL },
    { "ImprintingDMR.20220818.cm", "1dbab7ca0675c7602a1b829a671b92d6ef6e89abf7725187621857841281c9b9", 214, NULL },
    { "InfiniumChemistry.cm", "be8881082af3f61cbb1cfdf0cbcb2019bb147993ba04bf566e1b3f5ca3a74817", 4239, NULL },
    { "MetagenePC.20220911.cm", "358148ca3fc8a598a0bf53790ee51a7ec966a75684b259648a22fbad7424866e", 83185, NULL },
    { "nFlankCG.20220321.cm", "824bf96e203de0cf9ec3c0c4dcb1edac75f208e68ccc0fdbb1de3fa671c460d4", 26154, NULL },
    { "PMD.20220911.cm", "1ff8960b167a138219d329d01592c0a7f4850d5a83bb3c0f9d3f75054b00eb74", 12909, NULL },
    { "ProbeType.cm", "d4bffc89bd0e30c3189d4995ef847e51928a5676f01dbabee5f0a04a1c65cf0a", 94, NULL },
    { "REMCChromHMM.20220911.cm", "13b31d3e51fa026c0698805c8656421078d6da446ca19089135ded2bd2bcf2b0", 21534, NULL },
    { "rmsk1.20220307.cm", "ffad3bd277420c39496c359031812cc2b006bf88eef2c7c2a1b69c1bc49ec6fd", 2248, NULL },
    { "rmsk2.20220321.cm", "1cbc10f6575d4c5db5ac14f2d38500b4943a92402a2953ea06a9a44dd3aa5e3d", 2561, NULL },
    { "Tetranuc2.20220321.cm", "19d7076356377ed745cac3589a8c44a6cfda8079549a359f854824ca10d7f1e4", 12645, NULL },
    { "CGI.20220904.cm.idx", "a6dd837ca309339b916830c9840d23ca1e5b63b5a5c91b7c93ff2e4be4bdb677", 59, NULL },
    { "HM.20221013.cm.idx", "3443bc4c99e144752a8b607f0faf95013b6e672f3396729f03d48f478c76025e", 1562, NULL },
    { "MetagenePC.20220911.cm.idx", "c3a35ebb44bf0fd551cdbdbd252b9f44bffcdd94e7274ee93a78ba1aa62c3abb", 723, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_MM285[] = {
    { "MM285.ordering.tsv.gz", "6d199c9f5363ed00536f77165847f76bfe3ff7aac4fef1b409a4754f54dc1a6d", 2794476, NULL },
    { "MM285.mm10.coord.tsv.gz", "5e47aa327e69cdb7b360c975b7b9ddb38fa5c31059c30aabbb882370f298b4fa", 1284558, NULL },
    { "MM285.mm39.coord.tsv.gz", "6dc8783cd04ba9eb4cfa8bf637aa2851c3cb464951a6e0ba2d4f27bdd600cafb", 1283738, NULL },
    { "MM285.mm10.snp.tsv.gz", "caabb14f8d1a6e8158f1782a59aa3e60d6a62165cb202bc98853e96b9cd351b3", 766038, NULL },
    { "MM285.typeI_ext.tsv.gz", "4a5c2c0376632ced3a652a78f61d4d34fb288ba6418047a4b49a4efc9526882e", 32538, NULL },
    { "MM285.mm10.mask.cm", "aafc155b36c4da8834bca30064cbdf75f126e11c5cb0b5c022c56119a87219cc", 169234, NULL },
    { "MM285.mm39.mask.cm", "6f8aed63c75ff0408997b437ff9c3aaf4c6a94223320ce11ce8e1f23aa1c1326", 10839, NULL },
    { "MM285.mm10.mask.cm.idx", "8d5f95f871c81ae4824cb76a295c1369d9ed1a576d99fb3568cccf94a26031d2", 3027, NULL },
    { "MM285.mm39.mask.cm.idx", "1951a3cb4bc03fde4a7e4b42f09885c97b6d7f8b91eb05f24f239c8bbea3a3b5", 52, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_MM285_KYCG[] = {
    { "Blacklist.20220304.cm", "6acdc05addf7a398c6e542508e3aa921e3d773b1ab648899f68ce217b46a3999", 157, NULL },
    { "CGI.20220904.cm", "aa84355ea80709492f36926de2ccff201bc4dfb083a4275bc69b70517ee1f803", 62263, NULL },
    { "ChromHMM.20220318.cm", "405d6a9f9cebb612f3093c99b17619a089e07c16c020964079c3658184795003", 105535, NULL },
    { "Chromosome.20221129.cm", "b514638f7bfe8312a624dff191fd90079e4f54219635cc78e565f00ba80bb784", 3796, NULL },
    { "EnsRegBuild.20220710.cm", "2885a82f4996677863cf8c3f8b5b5555c9729837fa538b82f2c0ea9dded4eae2", 80521, NULL },
    { "HM.20221013.cm", "e73fe353a964ed3a47241d87c92905530b440c2590e24759dd7432b1bb71f7ee", 682801, NULL },
    { "InfiniumChemistry.cm", "05afd2b1631078fdd9007f22d23d8630c6e847a647266db73f3d91fe79e8a5dc", 70003, NULL },
    { "MetagenePC.20220911.cm", "465befca6c4f7f6157594921555127d0c252b8e67d5b1c77be074b290020f34e", 405122, NULL },
    { "PMD.20220911.cm", "f27098395cbd0b73d95805b117fe9e919ab54b0b7a7e3910b590ec057deb89dd", 11255, NULL },
    { "ProbeCGnum.cm", "af2fc3091380ba81251080487228c03312c9f549d0ef43e92937bd4dc4ea61c1", 108976, NULL },
    { "ProbeType.cm", "d36b5a465b32f72be1c3f94c91e070453a942da72fc79be7992df4eaa4c0c371", 92, NULL },
    { "TFBSrm.20221005.cm", "e172ee96f167e924526d49855f1cbb7c65816f5ef709a48e068f6190925ddd88", 5679253, NULL },
    { "Tetranuc2.20220321.cm", "63d33237a5e1645a78da60c11f23d8f0b03e1b26686d11733ef67c66fac4d2e1", 92597, NULL },
    { "Tetranuc4.20220321.cm", "e00763b660c4898b566b97f867e134ec0cbe7f87aff8c4e582f1107fee83f830", 175418, NULL },
    { "nFlankCG.20220321.cm", "5848fe5449c2bb1d20dfbdb6842f73464e93a5c9c3690b744202ccb056e14f89", 170331, NULL },
    { "rmsk1.20220321.cm", "df1acac0d34e38a4be76c6a965325fdfe9f00e3a97f58426e130586e3b6c87bf", 45136, NULL },
    { "rmsk2.20220321.cm", "119bdde120cbd02be80bebeedc1f024102567328593c47a14b24ede045626f04", 66744, NULL },
    { "CGI.20220904.cm.idx", "8572934f6587545c3374d2811e05b267b5d3f747453cbebabfe9f883f8994812", 62, NULL },
    { "EnsRegBuild.20220710.cm.idx", "42b06c9e6f1dd038d2af61bb9a4a6345fb95b9376b60a6f7d4a9ab95f77d8d25", 142, NULL },
    { "HM.20221013.cm.idx", "ddaed8ec814d4519fb5b2d2c4ccf9042c08fb05f9bff9eea9d3dc61d12919082", 1546, NULL },
    { "MetagenePC.20220911.cm.idx", "897ed2e9751f78a8d50d54fc759ac930c9d6955cf71c06d3bb7d7605a8220642", 747, NULL },
    { "TFBSrm.20221005.cm.idx", "d3ab150726e662b0e4967eff8e6e134acfaacc5a76cfd19678388da029392bbe", 11842, NULL },
    { "rmsk1.20220321.cm.idx", "aecf0f78c778d622797070014a451dfe5cc2b511ef017e510490d4ba540cfb10", 351, NULL },
    { "rmsk2.20220321.cm.idx", "86acb2e3d69cf7ea30373a069e9c9b9ac5db2782bf83883f3263e9421d01fed4", 983, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_MSA[] = {
    { "MSA.ordering.tsv.gz", "f89fa5ff525b4fd08b9c24303eabf8dc697fadbd4f35a1b606d19e4fb2199b2c", 2920535, NULL },
    { "MSA.hg38.coord.tsv.gz", "08f4c9a307cbbc271007c6d1318435df9877d04cd46a3f9a8e2c80d6529227fc", 1617785, NULL },
    { "MSA.hg38.snp.tsv.gz", "e0521bdf0598efb9205edee4bdc0ef7ba36ada73870a7eedaebaa3954c9158c2", 1065396, NULL },
    { "MSA.typeI_ext.tsv.gz", "b261dd9f956946fa1ea7fc224f18dc3a9c34573f6e9c2853b6202cc0cc679410", 30536, NULL },
    { "MSA.hg38.mask.cm", "928e9f782e7d23bd33d81e073f7185d957f3f1b1dad27691dc37f2f0aa1d178e", 156578, NULL },
    { "MSA.hg38.mask.cm.idx", "b6c0d7a80c3e5442df60fd6be5d90b84ecc45d55092a71e642769a70ac8dcc90", 774, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_InfiniumAnnotation_MSA_KYCG[] = {
    { "ABCompartment.20220911.cm", "af848881cb200450d1609bb12a8611966355ca846d64d4a9c4fcc69735c1761c", 119799, NULL },
    { "Blacklist.20220304.cm", "1c01c88d8b3ba4086954d1cae090f4ce340af27d524f9073e8dd7e16fad8662c", 663, NULL },
    { "CGI.20220904.cm", "9274d57343b7c3e69d574c1c8171a7696e42dd6f5dae02b62e85caabcf31ed37", 95101, NULL },
    { "CTCFbind.20220911.cm", "ccb2c1faccca56358a50c710b53c2e60edbc78c953ab308e2fb75b905fb10b5f", 9618, NULL },
    { "Centromere.20221129.cm", "f922a61fb14f6ef056b4657d7caeee72818abf0f935dddb7c3cbc5121a69c5c0", 2637, NULL },
    { "ChromHMM.20220303.cm", "2d6694f058c6846375574c81eb06d18003367ef51403f4049c4cbb5892b30700", 137462, NULL },
    { "ChromHMMfullStack.20230515.cm", "0ecfb617841fe24cde568574b8e7e86a66d4ce77bcffa7243f0695d2d394556f", 409143, NULL },
    { "Chromosome.20221129.cm", "afc63aeddefb7964f95745a381c2750015ce48982b1fe66d6e90f4b04251d193", 175568, NULL },
    { "CoRSIV.20220309.cm", "397239e997de5b2a05bf4166ffea3ceff2769977b5e89bbf034893c66f73f16f", 4682, NULL },
    { "EvoCons.20220314.cm", "898f8710f5f26e4f97da291b893d52edd798537cb68f88af3b1a8a802a4e961e", 30608, NULL },
    { "G4peaksHighConfidence.20220719.cm", "b91862a65c78a70248fc7bed7af42a609640520ce25d69b924571a6cf6f47179", 5291, NULL },
    { "HM.20221013.cm", "f3720d4ddd163d4864b21dfa500613725a4a083a313aa502f665f4c05a515c85", 615728, NULL },
    { "ImprintingDMR.20220818.cm", "25e9ea3802167725ae1881a83b51f79736c720de327fc965a46b8546e7a94446", 1662, NULL },
    { "InfiniumChemistry.cm", "327f44486df0fccdaddbd5499a39c4724e6d789fba027808756fea1ca858e658", 78457, NULL },
    { "IntergenicCpGs.20220811.cm", "6a431901e0dc531103ccdbe926cd0308eaa91781420d1eacd06832faa866a75f", 38194, NULL },
    { "IntermediateMeth.20221121.cm", "1e3472cbc0e4b9432b27e15d4f30f4d81f937cbaf5bf5c5618f4fe847024100b", 6787, NULL },
    { "MetagenePC.20220911.cm", "540b014f062595b1959e4da56e4557ed0d3ba446f12a85e3036e511b453959ca", 565940, NULL },
    { "PMD.20220911.cm", "2b81d76cccf50630f6003778cf7a2a139a3b3ebfb88b27ebb93f4bbb463f3632", 83724, NULL },
    { "ProbeCGnum.cm", "f455e783e0bdf245fd06a69689f70f29ea002316fb2ba11f5aef67b7d04f815c", 124614, NULL },
    { "ProbeType.cm", "ec3ba2e2f3237e2ee832e6600102ac9b366810b29d1ac4e1b014ec822fcbf3fa", 98, NULL },
    { "REMCChromHMM.20220911.cm", "0ff4f178a55c4eeca5d78e8935933bbf407f5f75852ed31d3ebae8f82477eac5", 138175, NULL },
    { "RoadMapNegGeneExpCpG.20220814.cm", "f8205c0ecfe280b6c2f5573b5e4cd6c6ee058b2dfc110d9b326f3fff8f8f9ddb", 17190, NULL },
    { "RoadMapPosGeneExpCpG.20220814.cm", "6dc87b392abdb32435d4dc2c7e48a1e70fd97c18a0375fa5e06aa854cbf1c655", 12466, NULL },
    { "TFBSrm.20221005.cm", "c1865cac9c6b140ba3ee4874f9f3abb95802b7e6ad8dfff0bd12d0e611c98893", 8876359, NULL },
    { "Tetranuc2.20220321.cm", "fa68a87bf41faa9f53c391b7cf25885e94ac6b5278ce96e448f53d8235bd3527", 90356, NULL },
    { "TiSigBLUEPRINT.20221209.cm", "9e30a16909ad1b9a97e6c220960852db755554ac269db6d1d1017ff2d565791c", 809075, NULL },
    { "TiSigBrain.20221209.cm", "1ba7b7125f315469564e2c7495ea66941ff59cf814f8a1006f43c9ac332fc35d", 1188786, NULL },
    { "TiSigLoyfer.20221209.cm", "e5ca7374a11f2688652ade4f06cd45fcee2a1ac25c3b58f21ce0dd33cd115f6c", 603728, NULL },
    { "XCILinkedWGBSSorted.20221121.cm", "ff1c2b2ced88a5f268654f72ce26a70d7e4170d5dd50c7adfe4de522434afea4", 2585, NULL },
    { "nFlankCG.20220321.cm", "0315823d430cdb5732cf337fee8d0b7cf4b7a0a3652fc58ca6162a611274bed8", 196667, NULL },
    { "rmsk1.20220307.cm", "e9cba20a5ffe4c52f3754f3497db10a31aff5f1944f288407536b83cafe5a16d", 61470, NULL },
    { "rmsk2.20220321.cm", "30dea7fa5b66dce40b74757337a2878d47aa59ed220f39d1629351c2ecb74fde", 89649, NULL },
    { "ABCompartment.20220911.cm.idx", "358466d28bc40ce9628c3fe74450aafe0c2ec18c6fd0cf66898ed4dec8cd9f83", 75, NULL },
    { "CGI.20220904.cm.idx", "472d4629f20d6b734dac0e5d2411e69edad459368c198e83fbb5f01d0c702827", 62, NULL },
    { "ChromHMMfullStack.20230515.cm.idx", "c67b37ccb53d4c641abe2ff809001e73a63d69448c39e94292c7b95ee2058bb1", 2080, NULL },
    { "HM.20221013.cm.idx", "5b368a172d057a1920ee19b52c15cd7039c8daea846877006e3a10fad20d98b0", 1655, NULL },
    { "MetagenePC.20220911.cm.idx", "25b236f5dc76642dd56f45bd89b0162800b7edd616fea0d180f716943f8fb304", 750, NULL },
    { "TFBSrm.20221005.cm.idx", "9e4d35098c228053c769ca6a0a49d904416dfd021b5f8af251b03b652ac25ac1", 22563, NULL },
    { "TiSigBLUEPRINT.20221209.cm.idx", "e3a450f4e7f7f63f90650167f768939ccfa231baf4203bc69b82d77817485e32", 19769, NULL },
    { "TiSigBrain.20221209.cm.idx", "4107494281e3110612a1247fbd9a9da5bcce748fe4ea6180d2da08fbb1257973", 12844, NULL },
    { "TiSigLoyfer.20221209.cm.idx", "d9a5c1b2ebfefe0538228c88ebbab421411987e6ede265b49f99ba02aa1a352c", 14818, NULL },
    { "nFlankCG.20220321.cm.idx", "2c23b4f0f1d5cdda05d32d8a8ee99f25130fda587db08eb7728f16a244d9bcf1", 420, NULL },
    { "rmsk1.20220307.cm.idx", "822aa08bb432a9657aabf5b939527f5c174a17f4ae4cdccfa9a76b40c2347892", 324, NULL },
    { "rmsk2.20220321.cm.idx", "e6523b87d1a6ea4e8a43b1cbb3f97859c213f52fc0d0b275960537dea75e43ca", 1038, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_KYCGKB_hg38[] = {
    { "ABCompartment.20220911.cm", "40a2eb1ec3b125f24c0ef81015da49e270a930dede9f9217a9d9afe253870143", 9763, NULL },
    { "Blacklist.20220304.cm", "338811096b7b17e0366a8240b144d264c734aa994b4d26234bc33f9d9c2ff814", 3142, NULL },
    { "CGI.20220904.cm", "f58c1b541e73511411cdf2820b1a2626d981baa8694453abb6334145e178af39", 206746, NULL },
    { "CTCFbind.20220911.cm", "d015f3169268e017a839c2405b48ae8ceda984d1fa3a6657641b9886d2707b8b", 163001, NULL },
    { "Centromere.20221129.cm", "70c204824ca015d3a7c76ed9ff0c13a65cd885335515e45bda5c32541a440c51", 347, NULL },
    { "ChromHMM.20220303.cm", "c38ff4081fad37d4678e97c72264e1b80fd2cfb2a5377a5392c07e37f4f3e160", 529428, NULL },
    { "ChromHMMfullStack.20230515.cm", "8dedbce6a2a1aa9a7323f584b97b0c987a79ddb1f3fef31d0bd863741b509e7c", 7086738, NULL },
    { "Chromosome.20221129.cm", "d7f036007c070e7953d92dd2c038c893e2a17c097a3f57e9506ef9280b9c188d", 298, NULL },
    { "ChromosomeXY.20230901.cm", "82486b531e00037137f7c430a4787b3194afd0d6bb6b7390fcb4265436f083ec", 99, NULL },
    { "HM.20221013.cm", "549dd34d6f60f3b122820d1852ae577b2da8478f2c537f776bbfe7d07354356a", 7540196, NULL },
    { "HM.20221013.cm.idx", "79fd3900b8dc3d8209e55c0bd0531f785754972492d2c2e948f4558788ef3669", 1741, NULL },
    { "ImprintingDMR.20220818.cm", "67e2e2b97b588b7d3383144714719ccf8559407e3ea6c0822db1dae92a4ab04e", 907, NULL },
    { "IntermediateMeth.20221121.cm", "d227908cd3539564a607bf0379eb93d39ed401866546332122bfdd4587b9c9a0", 26683, NULL },
    { "IntermediateMethS.20221121.cm", "ecd22e0c89e80a33a18e834a4df39e7c8a947b25d445a442a62b1f5adb4748c4", 18515, NULL },
    { "MetagenePC.20220911.cm", "48318c3a9a2649f87c6d4bce7b85331f22b923e76489f64db1d3a03f5f1647c1", 2971260, NULL },
    { "MetagenePC.20220911.cm.idx", "65d070eb420369a892dc208acd71f00d8862994bc31e89ee8cf92e8fc605e4c1", 712, NULL },
    { "PMD.20220911.cm", "025005aad8131ae8b1f843ad08ba218dd2c8d5bdfa95e3a552b50583cf9ad4b1", 18325, NULL },
    { "REMCChromHMM.20220911.cm", "0057271b80dfa5134cba1891dd0ddacc0518ee803c629615e3642d38aa7035f4", 490826, NULL },
    { "RoadMapNegGeneExpCpG.20220814.cm", "5a8154b7da8016e024348dcb556cc4c5b429fb9973843698871428a48f194d93", 463285, NULL },
    { "RoadMapPosGeneExpCpG.20220814.cm", "29aa056e65283aee666b95eb54d767db14284c57b79c67754f97796b9f265514", 570095, NULL },
    { "TFBS.20220921.cm", "d218d34191feeb5c8f04f8b083da173f033f20441a81f4c7d090b3a046414a2c", 90986293, NULL },
    { "TFBS.20220921.cm.idx", "f2de43e3ff5ebe53de10005b48bc6476225c99863a2767f843dd3b25781b1d6f", 27056, NULL },
    { "TFBSrm.20221005.cm", "360a2048c9cb2f45c9992ac3b3a14264c6eab0edbc6a43e954102b10016d13ea", 82231076, NULL },
    { "TFBSrm.20221005.cm.idx", "2ec6d39f1359dbb8ba5ec95525b29f9380b89c10417d4f535311afd78d56dc3c", 23731, NULL },
    { "Tetranuc2.20220321.cm", "b44a0827f4b3b3db5a15845aec6230b05cf3b60ab68f55aa6efefc60ecfc21c9", 9086753, NULL },
    { "TiSigBLUEPRINT.20221209.cm", "3facb90c0529eb34cee644b288134a5465d62be006d7d12657d79bd0c4d809d5", 26949077, NULL },
    { "TiSigBLUEPRINT.20221209.cm.idx", "b0f854de1aecc7a76b3e9f41b0fcd8b7bcedc22dad0d4acce52fce2ea8f2df96", 22418, NULL },
    { "TiSigBrain.20221209.cm", "3ceb5da27d9c1ae15fa4e5b21b4530512290a001c9d734dd6d62705efd087b62", 52404903, NULL },
    { "TiSigBrain.20221209.cm.idx", "fbad5e030427f55c5842fa99535b5e0f76d1577fef3be4c588bd7986c348c1da", 13414, NULL },
    { "TiSigLoyfer.20221209.cm", "8aa7570049b530214e866c8d00ee31b653790b0b0ef74c3e6c4e3960a6b45301", 28806752, NULL },
    { "TiSigLoyfer.20221209.cm.idx", "9de62d64fcb18caff6c1eb1f8ad7f4d131b24819ef36df668883389b25f37e6a", 16421, NULL },
    { "Win100k.20220228.cm", "585a9a0651029500cb1978d001069189b1fe368949715c99ad09fd91cb28e09a", 169101, NULL },
    { "XCILinkedWGBS.20221121.cm", "3bb5f15cf2da91c88e47ae021b6e75fdf9c3eb2b05aedfd0b6c479639b903864", 12552, NULL },
    { "XCILinkedWGBSSorted.20221121.cm", "89a38ce3ebc823e99aaed42ab6b9c9cb475bc069a41a8f43aedcef529a4f151b", 16744, NULL },
    { "cpg_nocontig.cr", "83cc96061b61ad3f7a83097705708b898b749ff0d00f9790b1f91a236a1298cd", 30318472, "hg38" },
    { "nFlankCG.20220321.cm", "a147624564e424b2ceabefe3da3263873e1a180ff8dba446adc794b96a110541", 11529528, NULL },
    { "nFlankCG100.20231025.cm", "d5744f66f94082836c8558c023f1ae98d809f935f6b2b00891673d546489f78b", 10120992, NULL },
    { "nFlankCG50.20231025.cm", "576d1b87764dec5511dcabad2a0342b1fbcbd0a9ccc2b771d7aa427e495ca116", 7572753, NULL },
    { "rmsk1.20220307.cm", "ca9d036591c2d0fd2220e5cc23cbf62458ea935f372d2d316118b9c7fa601d11", 4645990, NULL },
    { "rmsk1.20220307.cm.idx", "34a158c8e5df7bdba4a0dd42fd420a463415241ce79e2305face7b8855ff7ac4", 361, NULL },
    { "rmsk2.20220321.cm", "c613dec87a2705587f1f31ce85f57596e6823a792d773ef5f17c5c40bba8ccfb", 5749686, NULL },
    { "rmsk2.20220321.cm.idx", "c24e45bb151cde75b7308332f014b3768589aed4241b6dfd9804e6c011d9793b", 1212, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_KYCGKB_mm10[] = {
    { "Blacklist.20220304.cm", "60fde734e169212cf0a2b48dadcfcdf5d5a463d48934e239383d062ac91e7782", 636, NULL },
    { "CGI.20220904.cm", "99c3ede80a2d7833bc5c95405ec073f879587329cfbcc0e225a9224cf2a556f6", 122892, NULL },
    { "ChromHMM.20220414.cm", "49a6a884892d92145b6f1e2ef5120e8338f1228a9ecdc9dd5edf9fbdb0d66bd8", 877986, NULL },
    { "ChromHMMfullStack.20231222.cm", "167273200542ac80e6d4b10f17a8d5d9a3fe221acf077d59bd33349b26c78c1e", 6409786, NULL },
    { "Chromosome.20240119.cm", "07ee1c950d1cf639e2af7e79290e6efedc6f27e3082a4c6d6af708b1b9e50e69", 269, NULL },
    { "ChromosomeXY.20230901.cm", "fa7db61b687c1366367f6061f240ff107d8b9a2aa9f5871da8f1cc9c3ab9393b", 95, NULL },
    { "EnsRegBuild.20220710.cm", "4dd2d95dfaa0b8ed56115b426ef4ea7c2c2c50d1a39b5d5e77d2b8c57e371d59", 1019167, NULL },
    { "EnsRegBuild.20220710.cm.idx", "dbfe13ecd92283c834feee943d07d2fa39878d95bce1be4b734f97e3dd83274c", 146, NULL },
    { "EvoCons.20220314.cm", "fc92ab0c8a360db4eb2d78e38a0af71cf0accb0f92c3dfca8e5237b0172d1a2f", 115742, NULL },
    { "GCfrac.20220323.cm", "6b8ea23effd7b1f5931ec20d1f2cea1b8f069db4323c2e62a55fd5f3a881769e", 19989460, NULL },
    { "GeneFeatures.20220710.cm", "a04d79b323fc6c39860cfda662dda3cd4543eca91b17967c58ddb57e2bdbf026", 1476841, NULL },
    { "GeneFeatures.20220710.cm.idx", "a183002284431031f95610f032131f87e1ac7a3d31195ecf03dddb6f7a9454c4", 123, NULL },
    { "HM.20221013.cm", "d978b1ceca80b07ec0900ae7460eeacf592cde5a63a8b19dd1260abfa6ad8ffa", 5896537, NULL },
    { "HM.20221013.cm.idx", "4740f44bcb8adb27e11330a485219405ad128a17adeef2e5520d00b868391e45", 1632, NULL },
    { "MetagenePC.20220911.cm", "c4c99902a83a6a9a418f1cbc8b92eb226bd138eeeb5d8a54c6c54bfc627e0ba0", 2487844, NULL },
    { "MetagenePC.20220911.cm.idx", "5b6fa3313374543b52119d6847444416e0d7805d4e636e93c121421d7fde35b7", 709, NULL },
    { "PMD.20220911.cm", "8ce8a76d9a0efef3644ea096cc3ab6459b2f0513e1feb3f8fdb52c9be938af86", 16659, NULL },
    { "TFBS.20220922.cm", "8884906cf616914dc02cf4098afe6cd08b018ae7ee09a0642b3de6e4a013ef49", 56669024, NULL },
    { "TFBS.20220922.cm.idx", "e502a5b124755ce905381d96e52b132460ffe762d1a7665a014613a238f187a8", 13700, NULL },
    { "TFBSFreq.20220922.cm", "09eb2d20f0b126894d8823b30ade2106546d4d791ca4cb082ab333d57ca1c4fb", 3895475, NULL },
    { "TFBSrm.20221005.cm", "bb32723175ca5b788d18dcf0f9019e6c5e0340a11a1cac37f080c9e0dfc2d3d8", 53395935, NULL },
    { "TFBSrm.20221005.cm.idx", "8f6b6bdd36ed4251cdfd7fc5dc1eaa894b636be665678181febf2249f0cf14cb", 12454, NULL },
    { "Tetranuc2.20220321.cm", "18c99b9abeb11862b97fc0fdb12549c6e1e311daf82daf16487dbe946f8c87b8", 6838695, NULL },
    { "Tetranuc4.20220321.cm", "46d1c0ae912013c16fc8715e0fbbe6ff21d5235bf6435ce7f7afe64f9603ee6b", 13157336, NULL },
    { "UCSCEnsemblRegulatory.20220727.cm", "1d94928a7055eaa5a120777f950162d584d95aa605f53a6658c3e60c9de9c698", 639680, NULL },
    { "Win100k.20220228.cm", "83349a6c2888e98a34f20706f4904d4ac0973d447f7003ef1439f60cf0a1f912", 154709, NULL },
    { "Win1m.20230709.cm", "534f4a2cba8ef98e66f2b330878c7829a0556a5c8dd2a4ef6d6bd54af339f126", 16962, NULL },
    { "Win30k.20220228.cm", "e2ac4cfc01d9ed7099f3fb27226ddf7e65ff5a6ea1be7911c243efe7e2d4b00d", 513471, NULL },
    { "cpg_nocontig.cr", "bef068ffeb6293acf16449f986df89005b0dfc2f0cec8fae53fd57cbd8fc8224", 23825886, "mm10" },
    { "kmer10.20231109.cm", "8d3dd1d6581f125679732d3c3be89feba51499e7a5747e12514c212f42b79854", 52445331, NULL },
    { "nFlankCG.20220321.cm", "2c53fe47e2d7b3c01b2a7eadb97a17da75f8bb74a2ea19dd14383e990928a2a4", 7763796, NULL },
    { "nFlankCG100.20231025.cm", "fdc1fcc9b9c8e88fbc0ad0ab3e3d671fa4023a355c15d28676c492add3152205", 6787893, NULL },
    { "nFlankCG50.20231025.cm", "98fc285b6ae0501fb52d32b7604422ff418678bbf79859604906e77a6244ffdb", 5037900, NULL },
    { "rmsk1.20220321.cm", "d41f69ddbb46bb12945f55fc11816616e5aec89bca805279799528fcd3f5c073", 3321298, NULL },
    { "rmsk1.20220321.cm.idx", "c16a31dbdee08569920cf88927a2e8f7426e4b838c74c223dad12990f0372e3f", 374, NULL },
    { "rmsk2.20220321.cm", "a6301d67f7cf3e86c4d702b816191bd3da69d79748b7f6af133a853a5481d44a", 4623244, NULL },
    { "rmsk2.20220321.cm.idx", "70a4e2e6bf1325a76a1f834e5bd4c6b66d92755816a81e24d8de659b6d66a65a", 1152, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_KYCGKB_mm39[] = {
    { "ChromHMM.20250102.cm", "237d39c512c81c5e6f2d543b034ae16999219fb594b9d9e83abdb63c5971fdff", 882311, NULL },
    { "cpg_nocontig.cr", "67b183a53a820a13303a4e793465d8012b106baed0f0098bf480f623b4bfe75d", 23857084, "mm39" },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_genomes_hg38[] = {
    { "seqinfo.tsv.gz", "fb0451cc3a142233e220154fd7af2961d0ff2e8ba1113ca2b5ff6a948680b9e2", 221, NULL },
    { "gaps.tsv.gz", "0585abdbf80263e8779f5cdcc24bcf8ed2f108efb738e8ba44ba9b3ac24d5733", 5185, NULL },
    { "cytoband.tsv.gz", "a49a0cf26294e04d12cf073edcf2bd512f231c2f30607105c2fc4157b6c149f1", 9645, NULL },
    { "genes.bed.gz", "0ec51c895e05475cafdce90e83ef72beae2eee06b3fbe5544821ebd56bb1d423", 10708528, NULL },
    { "genes.bed.gz.tbi", "fa4064aed5e8f89db296cdcea7f5b131f8c6c53b5e213614b27e386a8f30b8d8", 192014, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_genomes_mm10[] = {
    { "seqinfo.tsv.gz", "ed48effa987d844b514e7bfd237447a949191c149f95aba383604cdc463f2a9f", 203, NULL },
    { "gaps.tsv.gz", "91f3ec9b0856505819e357b0644be35840b37dc26b42afced0c80e3ceedf59fe", 4758, NULL },
    { "cytoband.tsv.gz", "a7bb429fb76b97a37654fde43ced186d6bff49f4564faef1650b4e12af12566a", 4129, NULL },
    { "genes.bed.gz", "0e4497a94a8830a2d386f66836f6fec7d0669fdf3ee8ec62f06196117d23e14e", 6823722, NULL },
    { "genes.bed.gz.tbi", "5f6b4acadd9e2badf5b6b91bf9f5cb8ce864553362d34044188e1a2ecd923ff6", 202003, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_genomes_mm39[] = {
    { "seqinfo.tsv.gz", "bdcee6698a3dd045e91b07a7be6ad36b0c5b372707a17fb33051c6a7a251027b", 203, NULL },
    { "gaps.tsv.gz", "002c5aa5e3efab25947e93847e397c4629057640bc635b512d07f26029dc2337", 2038, NULL },
    { "cytoband.tsv.gz", "20f66bce778c2d07c08362673f1c75dadf6290925182dbb099d693a8bc183634", 757, NULL },
    { "genes.bed.gz", "ce6c63a5ab350fd40e4b75ea1b5295745f70114cb19d5717e938a39f02b96ca2", 7047902, NULL },
    { "genes.bed.gz.tbi", "6002f81994af23a84d6df8c8aba152bb507ed88b0a66532a3d1ebee1f9192f10", 203709, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_methscope_hg38_data[] = {
    { "human_hg38_40_celltypes_chr20.cg", "259b05d9a0708727a800817566a6c8f165a1210f45a9ffae692a8cdcbfe08f2e", 41377893, NULL },
    { "human_hg38_40_celltypes_chr20.cg.idx", "e17bb044c67853f8954caaf1c6b77bf4ae1a7f7efb05280df796581ab1a0bca7", 2182, NULL },
    { "human_hg38_celltypes.cg", "705973c8cdd475dbee6947952bff38fe4dea7fb44dc400c33fa9df4a0bc29a96", 6402003, NULL },
    { "human_hg38_celltypes.cg.idx", "ca868d49a73c7adf650bd6d58dbe3bb7e37f1472eef9b125fa195fd7ac69bb02", 96, NULL },
    { "human_hg38_immune_mixture.cg", "9806da825b933d2475b3e1c07a5fc399e16279eb9ccd06f5031112304edfdbd4", 3644798, NULL },
    { "human_hg38_test.cg", "276fce3f98a2de653009a2cb489e5f9ea699234a1b72aecd1ea3ba03795554a6", 103698, NULL },
    { "human_hg38_test.truth.cg", "63dd50e9b86b8abcb4c70c4927fd766026aa29999268f407187c16acfb7f6f6f", 1944547, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_methscope_models_hg38_models[] = {
    { "hg38_10k1.updecx", "8f7f2d6d42f64daaba5bf9cede5146fa52c0f62b5c76b3d5c6680c5c7554b1b7", 29075778, NULL },
    { "hg38_33celltypes.msdref", "1e299d064423e4562e012b7ad92e9536e28010691cc37ec4a9ae4ed81f7c26ff", 0, NULL },
    { "hg38_celltype.clfx", "16c4e9ccc7fd5997a4676f50926f0257fffecb97424c9c4efc393984ef7170c3", 5738519, NULL },
    { "hg38_sex.clfx", "3d1618f6ca24d9a9d5b0fe1806673540515e5f6e7d7950e7c8873a85bb5c742b", 30931, NULL },
    { "hg38_wg.updecx", "60c786aa383c27461e7a5de37d6b17d2e01b33c5f8a6553f3df7083035fac65a", 2835749302, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_methscope_models_mm10_models[] = {
    { "mm10_celltype_brain.clfx", "c754eb20c03758678d7da861080b68461b636aded7be1544b38f23e0d6b04902", 0, NULL },
    { "mm10_wg.updecx", "f25cc5317a892105a121300fef009e29e96677f9a43fd02c3b47a59bf64cd482", 2057125237, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_pin_prior_t YAME_PRIOR_methscope_models_hg38_models[] = {
    { "v1", "6d1c5db5a545ffef909b734a9e9eeb1fed3922630aa0e026e063c8969ae32de5" },
    { "v2", "219d549b9020bb418199bb7f3c4884798bf68c65f82659495493c2fff8ade6e7" },
    { "v3", "88a4933866332ff63d95b08457fcb2ca772a6302e172b7f8c681c25ed8be0b6d" },
    { "v4", "d605a8265c107c5a5aa0d005eed32955b5ddeff54cfa55359fd952a52abb5dad" },
    { "v5", "3e1a6a51226e80c696c4149f620030a83d3cd6ac96bc74a74a95852b68180eb0" },
    { "v6", "ad2cfa7d9d467d0900b81d27fc9d555c5863bb2b4ed16851f3ba23b8d4351180" },
};

static const yame_pin_prior_t YAME_PRIOR_methscope_models_mm10_models[] = {
    { "v1", "6d1c5db5a545ffef909b734a9e9eeb1fed3922630aa0e026e063c8969ae32de5" },
    { "v2", "219d549b9020bb418199bb7f3c4884798bf68c65f82659495493c2fff8ade6e7" },
    { "v3", "88a4933866332ff63d95b08457fcb2ca772a6302e172b7f8c681c25ed8be0b6d" },
    { "v4", "d605a8265c107c5a5aa0d005eed32955b5ddeff54cfa55359fd952a52abb5dad" },
    { "v5", "3e1a6a51226e80c696c4149f620030a83d3cd6ac96bc74a74a95852b68180eb0" },
    { "v6", "ad2cfa7d9d467d0900b81d27fc9d555c5863bb2b4ed16851f3ba23b8d4351180" },
};

static const yame_asset_reg_t YAME_ASSETS[] = {
    { "InfiniumAnnotation", "EPIC", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPIC", "EPIC", "b97d9481f07b5f39dc6424b55d686ba9baac66b80e6bfd11615a1db9ebb3b629", YAME_FILES_InfiniumAnnotation_EPIC, YAME_NFILES(YAME_FILES_InfiniumAnnotation_EPIC), NULL, 0 },
    { "InfiniumAnnotation", "EPIC/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPIC/KYCG", "EPIC/KYCG", "1678294f10134013db3fe274dfeb5243cd5e4352d40e01ef50528c91ac3b077b", YAME_FILES_InfiniumAnnotation_EPIC_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_EPIC_KYCG), NULL, 0 },
    { "InfiniumAnnotation", "EPICv2", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPICv2", "EPICv2", "3a0eb8523b1a1de3194846afaeff72d9ee907edae271952e34809b1f7dce5e30", YAME_FILES_InfiniumAnnotation_EPICv2, YAME_NFILES(YAME_FILES_InfiniumAnnotation_EPICv2), NULL, 0 },
    { "InfiniumAnnotation", "EPICv2/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPICv2/KYCG", "EPICv2/KYCG", "82c17bbc0b59fbf96545ea029cdc089a19214395d8d3f6e6826ee161b8b8eb17", YAME_FILES_InfiniumAnnotation_EPICv2_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_EPICv2_KYCG), NULL, 0 },
    { "InfiniumAnnotation", "HM27", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM27", "HM27", "2b070eb62e6818410bea118da3881ff211b78857fad73078a0403e8b9303eec8", YAME_FILES_InfiniumAnnotation_HM27, YAME_NFILES(YAME_FILES_InfiniumAnnotation_HM27), NULL, 0 },
    { "InfiniumAnnotation", "HM27/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM27/KYCG", "HM27/KYCG", "450bdb2bb74d152ba8d8b96646e6976122ebe00900d41e7aa67ebcadcf739b68", YAME_FILES_InfiniumAnnotation_HM27_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_HM27_KYCG), NULL, 0 },
    { "InfiniumAnnotation", "HM450", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM450", "HM450", "8ea679ca36fb0c0b1d4acce2843c9534b2a3dfca2656cd182187178d47dcac8a", YAME_FILES_InfiniumAnnotation_HM450, YAME_NFILES(YAME_FILES_InfiniumAnnotation_HM450), NULL, 0 },
    { "InfiniumAnnotation", "HM450/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM450/KYCG", "HM450/KYCG", "27e4d8ef73bcd1c8b75ddb0fc203e17218bd5de1b05e0bfc847b217621c308bf", YAME_FILES_InfiniumAnnotation_HM450_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_HM450_KYCG), NULL, 0 },
    { "InfiniumAnnotation", "Mammal40", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "Mammal40", "Mammal40", "f97bfab4f14ea58408cfc677ac8dfec20b5d54d2ec4b87700e8076b64745d7c2", YAME_FILES_InfiniumAnnotation_Mammal40, YAME_NFILES(YAME_FILES_InfiniumAnnotation_Mammal40), NULL, 0 },
    { "InfiniumAnnotation", "Mammal40/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "Mammal40/KYCG", "Mammal40/KYCG", "f49d45d83eac05f556595980aadba6cce39ee64172050f065a7b2137b73ea351", YAME_FILES_InfiniumAnnotation_Mammal40_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_Mammal40_KYCG), NULL, 0 },
    { "InfiniumAnnotation", "MM285", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MM285", "MM285", "c5d4d485c9b076bab7bedee903ba838d087a58f2d280d3300cc25c9ead6da0c4", YAME_FILES_InfiniumAnnotation_MM285, YAME_NFILES(YAME_FILES_InfiniumAnnotation_MM285), NULL, 0 },
    { "InfiniumAnnotation", "MM285/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MM285/KYCG", "MM285/KYCG", "2cb53129949cfce5f8149c6ab1321069f30a236757a3f4095c2e5e00b3c141e9", YAME_FILES_InfiniumAnnotation_MM285_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_MM285_KYCG), NULL, 0 },
    { "InfiniumAnnotation", "MSA", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MSA", "MSA", "16e0e3204cec42935a690860c849b8d259f29d9e634164e68f395607948a7c40", YAME_FILES_InfiniumAnnotation_MSA, YAME_NFILES(YAME_FILES_InfiniumAnnotation_MSA), NULL, 0 },
    { "InfiniumAnnotation", "MSA/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MSA/KYCG", "MSA/KYCG", "cc63264354f71f436e7aa4e7b9820430461e6923d657c54a24bb03cca4682db5", YAME_FILES_InfiniumAnnotation_MSA_KYCG, YAME_NFILES(YAME_FILES_InfiniumAnnotation_MSA_KYCG), NULL, 0 },
    { "KYCGKB", "hg38", "https://github.com/zhou-lab/KYCGKB_hg38/raw", "v2", "", "hg38/KYCG", "8e0594ade2936a7b837306cec8e4d29bb9028a6a3be5b2cdbd372af7c16f650a", YAME_FILES_KYCGKB_hg38, YAME_NFILES(YAME_FILES_KYCGKB_hg38), NULL, 0 },
    { "KYCGKB", "mm10", "https://github.com/zhou-lab/KYCGKB_mm10/raw", "v2", "", "mm10/KYCG", "fbb75f8198a731f3ea2de7d2fb65e92c84f4e0f0e2ff335b9ff2e2000606f289", YAME_FILES_KYCGKB_mm10, YAME_NFILES(YAME_FILES_KYCGKB_mm10), NULL, 0 },
    { "KYCGKB", "mm39", "https://github.com/zhou-lab/KYCGKB_mm39/raw", "v2", "", "mm39/KYCG", "0dfa2114daa79c8c5fabae2d4795d250266d48f7e941fd99e81cf459e72ead64", YAME_FILES_KYCGKB_mm39, YAME_NFILES(YAME_FILES_KYCGKB_mm39), NULL, 0 },
    { "genomes", "hg38", "https://github.com/zhou-lab/genomes/raw", "v3", "hg38", "hg38", "1d3cd57e1e6a5bfd504730b925d167ccd444d051ea004e0d09853618fa770507", YAME_FILES_genomes_hg38, YAME_NFILES(YAME_FILES_genomes_hg38), NULL, 0 },
    { "genomes", "mm10", "https://github.com/zhou-lab/genomes/raw", "v3", "mm10", "mm10", "0f3ea46ec5ed2408eb9e0579db074fce1f6aba60049b8d11e6e0ab37d5a1c539", YAME_FILES_genomes_mm10, YAME_NFILES(YAME_FILES_genomes_mm10), NULL, 0 },
    { "genomes", "mm39", "https://github.com/zhou-lab/genomes/raw", "v3", "mm39", "mm39", "50c5eb9a405d110182c75edfd87d5fff40345888cd86bd4bf5166573efac9727", YAME_FILES_genomes_mm39, YAME_NFILES(YAME_FILES_genomes_mm39), NULL, 0 },
    { "methscope", "hg38/data", "https://raw.githubusercontent.com/zhou-lab/methscope_data", "v3", "test", "hg38/data", "150e6ae8b929e59e5b49cec241683abe6e20614bc2d29bc00f083ee01da7e19b", YAME_FILES_methscope_hg38_data, YAME_NFILES(YAME_FILES_methscope_hg38_data), NULL, 0 },
    { "methscope", "hg38/models", "https://huggingface.co/zhou-lab/methscope/resolve", "v7", "", "hg38/models", "188fa1daac6b0068ae4a71b366b51a6c3c1c39129cdfb9b9cff9637105e347c9", YAME_FILES_methscope_models_hg38_models, YAME_NFILES(YAME_FILES_methscope_models_hg38_models), YAME_PRIOR_methscope_models_hg38_models, YAME_NPRIOR(YAME_PRIOR_methscope_models_hg38_models) },
    { "methscope", "mm10/models", "https://huggingface.co/zhou-lab/methscope/resolve", "v7", "", "mm10/models", "188fa1daac6b0068ae4a71b366b51a6c3c1c39129cdfb9b9cff9637105e347c9", YAME_FILES_methscope_models_mm10_models, YAME_NFILES(YAME_FILES_methscope_models_mm10_models), YAME_PRIOR_methscope_models_mm10_models, YAME_NPRIOR(YAME_PRIOR_methscope_models_mm10_models) },
    { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0 }
};

#define YAME_ASSETS_N (sizeof(YAME_ASSETS)/sizeof(YAME_ASSETS[0]) - 1)

/**
 * Row-space fingerprints: how many rows a file written against each reference
 * has.
 *
 * A CX record carries its row count and nothing about what those rows ARE, so
 * the count is the only handle on which reference it belongs to -- and it is
 * enough, because no two row spaces in the catalogue share one. That is what
 * lets a command infer -R rather than make the caller repeat what the file
 * already implies.
 *
 * `rows` is hand-pinned in the catalog: it is a property of a file's contents,
 * which no manifest carries. `fetch` is the argument that would put the
 * reference in the store, for the error message when it is not there.
 */
typedef struct yame_ref_rows_s {
    const char *name;        /* hg38, EPIC, ... */
    const char *kind;        /* "genome" (a .cr) or "array" (an ordering) */
    uint64_t    rows;
    const char *store_path;  /* the reference itself, under the store root */
    const char *const *dirs; /* every directory it owns, nearest first */
    const char *fetch;       /* the browser path to give `yame fetch` */
} yame_ref_rows_t;

static const char *const YAME_REF_DIRS_hg38[] = { "hg38", "hg38/KYCG", NULL };
static const char *const YAME_REF_DIRS_mm10[] = { "mm10", "mm10/KYCG", NULL };
static const char *const YAME_REF_DIRS_mm39[] = { "mm39", "mm39/KYCG", NULL };
static const char *const YAME_REF_DIRS_EPIC[] = { "EPIC", "EPIC/KYCG", NULL };
static const char *const YAME_REF_DIRS_EPICv2[] = { "EPICv2", "EPICv2/KYCG", NULL };
static const char *const YAME_REF_DIRS_HM27[] = { "HM27", "HM27/KYCG", NULL };
static const char *const YAME_REF_DIRS_HM450[] = { "HM450", "HM450/KYCG", NULL };
static const char *const YAME_REF_DIRS_Mammal40[] = { "Mammal40", "Mammal40/KYCG", NULL };
static const char *const YAME_REF_DIRS_MM285[] = { "MM285", "MM285/KYCG", NULL };
static const char *const YAME_REF_DIRS_MSA[] = { "MSA", "MSA/KYCG", NULL };

static const yame_ref_rows_t YAME_REF_ROWS[] = {
    { "hg38", "genome", 29401795, "hg38/cpg_nocontig.cr", YAME_REF_DIRS_hg38, "hg38" },
    { "mm10", "genome", 21867837, "mm10/cpg_nocontig.cr", YAME_REF_DIRS_mm10, "mm10" },
    { "mm39", "genome", 21889506, "mm39/cpg_nocontig.cr", YAME_REF_DIRS_mm39, "mm39" },
    { "EPIC", "array", 866553, "EPIC/EPIC.ordering.tsv.gz", YAME_REF_DIRS_EPIC, "EPIC" },
    { "EPICv2", "array", 937690, "EPICv2/EPICv2.ordering.tsv.gz", YAME_REF_DIRS_EPICv2, "EPICv2" },
    { "HM27", "array", 27722, "HM27/HM27.ordering.tsv.gz", YAME_REF_DIRS_HM27, "HM27" },
    { "HM450", "array", 486427, "HM450/HM450.ordering.tsv.gz", YAME_REF_DIRS_HM450, "HM450" },
    { "Mammal40", "array", 38607, "Mammal40/Mammal40.ordering.tsv.gz", YAME_REF_DIRS_Mammal40, "Mammal40" },
    { "MM285", "array", 287692, "MM285/MM285.ordering.tsv.gz", YAME_REF_DIRS_MM285, "MM285" },
    { "MSA", "array", 284309, "MSA/MSA.ordering.tsv.gz", YAME_REF_DIRS_MSA, "MSA" },
    { NULL, NULL, 0, NULL, NULL, NULL }
};

#define YAME_REF_ROWS_N (sizeof(YAME_REF_ROWS)/sizeof(YAME_REF_ROWS[0]) - 1)

#endif /* _YAME_REGISTRY_H */
