/* registry.h -- GENERATED by tools/make_registry.sh --tool=yame. Do not edit.
 *
 * What `yame fetch` knows how to download, and the digest each directory's
 * manifest must have. One row per fetchable directory: the store path is the
 * shared layout every tool in the suite reads, so a directory filled here is
 * found by kycg / sesame-cli / methscope-cli without any of them re-fetching.
 *
 * The anchor is sha256(SHA256SUMS) at the pinned tag, hashed from the copy
 * cached under tools/registry/sums/. Verifying a fetched manifest against it
 * is what makes every per-file digest trustworthy, and comparing a STORED
 * manifest against it is how a directory says which tag filled it.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2021-present Wanding Zhou
 */
#ifndef _YAME_REGISTRY_H
#define _YAME_REGISTRY_H

#include <stddef.h>

typedef struct {
    const char *source;      /* upstream repo family: InfiniumAnnotation, ... */
    const char *target;      /* platform, genome, or "<platform>/KYCG" */
    const char *base_url;    /* <base>/<tag>/<remote_sub>/SHA256SUMS */
    const char *tag;
    const char *remote_sub;  /* "" when the manifest is at the repo root */
    const char *store_sub;   /* path under the store root */
    const char *anchor;      /* sha256 of that directory's SHA256SUMS */
} yame_asset_reg_t;

static const yame_asset_reg_t YAME_ASSETS[] = {
    { "InfiniumAnnotation", "EPIC", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPIC", "InfiniumAnnotation/EPIC", "b97d9481f07b5f39dc6424b55d686ba9baac66b80e6bfd11615a1db9ebb3b629" },
    { "InfiniumAnnotation", "EPIC/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPIC/KYCG", "InfiniumAnnotation/EPIC/KYCG", "1678294f10134013db3fe274dfeb5243cd5e4352d40e01ef50528c91ac3b077b" },
    { "InfiniumAnnotation", "EPICv2", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPICv2", "InfiniumAnnotation/EPICv2", "3a0eb8523b1a1de3194846afaeff72d9ee907edae271952e34809b1f7dce5e30" },
    { "InfiniumAnnotation", "EPICv2/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "EPICv2/KYCG", "InfiniumAnnotation/EPICv2/KYCG", "82c17bbc0b59fbf96545ea029cdc089a19214395d8d3f6e6826ee161b8b8eb17" },
    { "InfiniumAnnotation", "HM27", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM27", "InfiniumAnnotation/HM27", "2b070eb62e6818410bea118da3881ff211b78857fad73078a0403e8b9303eec8" },
    { "InfiniumAnnotation", "HM27/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM27/KYCG", "InfiniumAnnotation/HM27/KYCG", "450bdb2bb74d152ba8d8b96646e6976122ebe00900d41e7aa67ebcadcf739b68" },
    { "InfiniumAnnotation", "HM450", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM450", "InfiniumAnnotation/HM450", "8ea679ca36fb0c0b1d4acce2843c9534b2a3dfca2656cd182187178d47dcac8a" },
    { "InfiniumAnnotation", "HM450/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "HM450/KYCG", "InfiniumAnnotation/HM450/KYCG", "27e4d8ef73bcd1c8b75ddb0fc203e17218bd5de1b05e0bfc847b217621c308bf" },
    { "InfiniumAnnotation", "Mammal40", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "Mammal40", "InfiniumAnnotation/Mammal40", "f97bfab4f14ea58408cfc677ac8dfec20b5d54d2ec4b87700e8076b64745d7c2" },
    { "InfiniumAnnotation", "Mammal40/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "Mammal40/KYCG", "InfiniumAnnotation/Mammal40/KYCG", "f49d45d83eac05f556595980aadba6cce39ee64172050f065a7b2137b73ea351" },
    { "InfiniumAnnotation", "MM285", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MM285", "InfiniumAnnotation/MM285", "c5d4d485c9b076bab7bedee903ba838d087a58f2d280d3300cc25c9ead6da0c4" },
    { "InfiniumAnnotation", "MM285/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MM285/KYCG", "InfiniumAnnotation/MM285/KYCG", "2cb53129949cfce5f8149c6ab1321069f30a236757a3f4095c2e5e00b3c141e9" },
    { "InfiniumAnnotation", "MSA", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MSA", "InfiniumAnnotation/MSA", "16e0e3204cec42935a690860c849b8d259f29d9e634164e68f395607948a7c40" },
    { "InfiniumAnnotation", "MSA/KYCG", "https://github.com/zhou-lab/InfiniumAnnotation/raw", "v8.1", "MSA/KYCG", "InfiniumAnnotation/MSA/KYCG", "cc63264354f71f436e7aa4e7b9820430461e6923d657c54a24bb03cca4682db5" },
    { "KYCGKB", "hg38", "https://github.com/zhou-lab/KYCGKB_hg38/raw", "v2", "", "KYCGKB/hg38", "8e0594ade2936a7b837306cec8e4d29bb9028a6a3be5b2cdbd372af7c16f650a" },
    { "KYCGKB", "mm10", "https://github.com/zhou-lab/KYCGKB_mm10/raw", "v2", "", "KYCGKB/mm10", "fbb75f8198a731f3ea2de7d2fb65e92c84f4e0f0e2ff335b9ff2e2000606f289" },
    { "genomes", "hg38", "https://github.com/zhou-lab/genomes/raw", "v2", "hg38", "genomes/hg38", "b64b320984c6d1d29dc1e15dd1a8a2ce109442eea703eba013d11ffb1eb8e975" },
    { "genomes", "mm10", "https://github.com/zhou-lab/genomes/raw", "v2", "mm10", "genomes/mm10", "0b9aed8b19ed9ead8d8c61b9bf5050e11f4c5278bf701d46b439857407142035" },
    { "genomes", "mm39", "https://github.com/zhou-lab/genomes/raw", "v2", "mm39", "genomes/mm39", "8f7bab6aa49cc2612b82d0f3b6e749eaff41d6ea925e8aff20b42269b47b9902" },
    { NULL, NULL, NULL, NULL, NULL, NULL, NULL }
};

#define YAME_ASSETS_N (sizeof(YAME_ASSETS)/sizeof(YAME_ASSETS[0]) - 1)

#endif /* _YAME_REGISTRY_H */
